### ISSUE TITLE
Examples should be standardized (same username)

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#27] opened 2017-06-18 13:19 UTC
We should define some standardized definitions to use throughout the document.

For example, there's already `\def\r/{\textsf{R}}`. Perhaps we should define `\def\userid/{userid}` to be used throughout? There are other examples, like `\hostname/`

I think you could get it to pass to the listings envornments, too. Something like the following:

```
\newcommand\terminal[1] {
    \begin{lstlisting}[style=terminal]
        \userid/@\hostname/:~$ #1
    \end{lstlisting}
}
```

I can begin a branch on this from Develop, but may need your help @dpritchLibre

**Comment by dpritchLibre** [comment] 2017-10-20 14:21
Somehow I've just now noticed this issue - probably because we've been thinning  out the list of issues lately.

I agree 100% that we should use a standardized format for the terminal prompts.  Probably the best way to do this is the following: the terminal listings environment has a way of escaping from verbatim into TeX commands (we have defined the opening and closing as `(*@` and `@*)`, using the `escapeinside` option).  So maybe we could do something like this:

    \newcommand{diam-prompt}[1]{userid@diamond:{#1}$}
    
    \begin{lstlisting}[style=terminal]
    (*@\diam-promp{mydir}@*) date
    Fri Jan  6 22:54:39 EST 2017
    \end{lstlisting}

One concern that I have is whether underscores and other special characters that should be handled literally in the listings environment will work properly when passed as an argument to `\diam-prompt`.  Would have to experiment on that.

**Comment by dpritchLibre** [comment] 2017-10-20 14:24
P.s. In your code example above, you always should add a comment character after open braces in TeX or else your spacing can get messed up.  So

    \newcommand\terminal[1] {%

not

    \newcommand\terminal[1] {

Do not ask me why.  This issue cost me several hours at some point when working on this project.

**Comment by BarkleyBG** [comment] 2017-10-20 14:56
I like this. 

I also like shorter function names. Maybe we could define `tp-d` "terminal prompt on Diamond" and `tp-ll` for "on Longleaf"? Etc. Of course, shorter is at the expense of readable.

**Comment by BarkleyBG** [comment] 2017-10-20 15:03
I like this. I'd prefer `\prompt-diam` over `\diam-prompt` because i think the first one is arguably a better explanation of the function's actions (or maybe just easier for me to remember)

I also like shorter function names. Maybe we could define `\tp-d` "terminal prompt on Diamond" and `\tp-ll` for "on Longleaf"? Etc. 

Of course, shorter is at the expense of readable.

**Comment by dpritchLibre** [comment] 2017-11-28 02:04
I've asked for some help with this on [this tex.stackexchange question](https://tex.stackexchange.com/q/403461), as once again, it is beyond my technical abilities.

**Comment by dpritchLibre** [comment] 2017-12-02 02:35
I'm not seeing any more movement on the stackexchange question, so I'm afraid that it's dead in the water.  The one comment on there did provide a workaround that would work; I've provided some example code below.  The problem is that it's rather difficult and annoying to read the source code.  I see two options:

1.  use the macros presented below
2.  explicitly codify what the prompts should look like in the CONTRIBUTING.md file and leave it up to the contributors (i.e. you and me) to follow the rules

Either way his means that we need to put our heads together in the not-too-distant future and make some decisions about this.  What do you think is the better option @BarkleyBG?

Image of compiled code below, then source code following that

---------------------------------------------------------------------------------------------------
![listings_macros](https://user-images.githubusercontent.com/12739902/33510787-bda99852-d6de-11e7-993c-235084a09f2b.png)

---------------------------------------------------------------------------------------------------

    \documentclass{article}
    
    \usepackage{lmodern}
    \usepackage[T1]{fontenc}
    \usepackage{listings}
    
    
    
    
    % define macros ----------------------------------------------------------------
    
    \newcommand{\promptLocal}[2]{%
      \frenchspacing\fontsize{10.40}{11.40}\bfseries\fontfamily{pcr}\selectfont{userid@localhost:%
        \detokenize{#1}\$ \detokenize{#2}}%
    }
    \newcommand{\promptDiam}[1]{%
      \frenchspacing\fontsize{10.40}{11.40}\bfseries\fontfamily{pcr}\selectfont{userid@diamond:\detokenize{#1}\$}
    }
    \newcommand{\promptSapph}[1]{%
      \frenchspacing\fontsize{10.40}{11.40}\bfseries\fontfamily{pcr}\selectfont{userid@sapphire:\detokenize{#1}\$}
    }
    \newcommand{\promptLong}[1]{%
      \frenchspacing\fontsize{10.40}{11.40}\bfseries\fontfamily{pcr}\selectfont{userid@longleaf:\detokenize{#1}\$}
    }
    
    
    
    
    % listings settings ------------------------------------------------------------
    
    \lstset{%
      basicstyle=\fontsize{10.40}{11.40}\fontfamily{pcr}\selectfont,
      commentstyle=\bfseries,
      morecomment=[l]{userid@},
      morecomment=[is]{/-}{-/},
      morecomment=[l]{(*@},
      escapeinside={(*@}{@*)},
    }
    
    
    
    
    % ------------------------------------------------------------------------------
    
    \begin{document}
    
    \begin{lstlisting}
    userid@localhost:~$ echo hardcoded
    hardcoded
    (*@\promptLocal{~}{echo using macro}@*)
    using macro
    
    userid@diamond:~$ echo hardcoded
    hardcoded
    (*@\promptDiam{~}{echo using macro}@*)
    using macro
    
    userid@sapphire:~$ echo hardcoded
    hardcoded
    (*@\promptSapph{~}{echo using macro}@*)
    using macro
    
    userid@longleaf:~$ echo hardcoded
    hardcoded
    (*@\promptLong{~}{echo using macro}@*)
    using macro
    \end{lstlisting}
    
    \end{document}

**Comment by BarkleyBG** [comment] 2017-12-04 01:07
We
 - [ ] need to choose what we want the words to be
 - [ ] need to choose whether we want to use the macros or not

**Comment by dpritchLibre** [comment] 2017-12-09 20:20
@BarkleyBG I request that you kindly make a decision about this ASAP, since I plan to begin revisions to chapter 2 soon.

As far as the style of the prompt, I'm used to seeing a prompt that looks like the following.  However if you have a format that you prefer, I'm totally happy to go with that.

    userid@hostname:/working/directory$

Then we have to choose the username and hostname for various situations.  I will try to enumerate them here.  Let me know if I missed any

**username:**
*  generic
*  local (when we want to differentiate from remote ID (i.e. Onyen) in chapter 0 or elsewhere)
*  Onyen ID

**hostname:**
*  generic
*  local (when we want to differentiate from remote in chapter 0 or elsewhere)
*  Diamond
*  Sapphire
*  Longleaf login 1
*  Longleaf login 2

**Comment by dpritchLibre** [comment] 2017-12-09 20:36
Let me offer a few suggestions to get the ball rolling, and then please go ahead and make some revisions as you see fit.

**username:**

| Type    | Definition |
|---------|------------|
| Generic | user-id    |
| Local   | local-id   |
| Onyen   | onyen-id      |

**hostname:**

| Type       | Definition      |
|------------|-----------------|
| Generic    | host-name        |
| Local      | local-host-name       |
| Diamond    | diamond         |
| Sapphire    | sapphire         |
| Longleaf 1 | longleaf-login1 |
| Longleaf 2 | longleaf-login2 |

**Comment by BarkleyBG** [comment] 2017-12-10 15:33
Yeah, let's do something like this. 

I think we should add an appendix with short descriptions of, say, the differences between `localid` and `onyenid`. Then, every time we need to use the different id's then we can refer to the appendix for clarity. 

A made-up example:

>To ssh on to the cluster, you would do type the following commands from your local machine to log on to the remote machine. Note that the id's and hosts are different - see the `\autoref{appendix2}`:
`userid@local_host(~) $ ssh onyenid@remote_host_name.com`

**Comment by BarkleyBG** [comment] 2017-12-10 15:37
I like the list of type/definitions that you have. I would prefer underscores to dashes, perhaps.

Should we start a `style_guide` or add this info into `Appendix_2_hosts.tex` or something? I think an appendix would be good. Shall we add that before you start with your chapter 2 edits?

**Comment by dpritchLibre** [comment] 2017-12-10 17:35
Yeah, I think adding a little section to the appendix about it would be really nice, as in your example above.  And then in CONTRIBUTING.md we could give a brief overview and refer people to the appendix perhaps for the definitions?

I tend to prefer underscores to hyphens myself, but for whatever reason I've always seen hyphens for usernames and hostnames and have never yet in my fledgling career seen an underscore used (case in point: the Longleaf login nodes).  I don't have strong feelings about it, it was just written to try to follow the prevailing convention.

Update: actually, I just looked it up, hostnames on computer networks are only allowed to have alphanumeric characters or the hyphen.  Usernames can presumably be whatever characters you want, but I think it would be ugly to mix the styles.

**Comment by BarkleyBG** [comment] 2017-12-10 17:42
Sounds good! 
- Hyphens are fine for the hostnames
- i think we should not hyphenate usernames. I think `userid` `localid` `onyenid`  and `remoteid` would be more clear than `user-id` and `onyen-id` since `onyen-id` is not a valid onyen, i think.

Do you want to create an appendix with the hostname/userid stuff? If you post and PR then I can merge today and we can move along so very merrily

**Comment by BarkleyBG** [comment] 2017-12-10 17:43
BTW I just pushed and merged a few changed to develop branch, so pull first

**Comment by dpritchLibre** [comment] 2017-12-10 17:47
Okay! Agreed on the usernames!!  Yeah I can add to the appendix..

We still need to make a decision about whether or not to use a macro for these.

**Comment by dpritchLibre** [comment] 2017-12-12 00:01
Updated version of the user/hostnames

**username:**

| Type    | Definition |
|---------|------------|
| Generic | userid    |
| Local   | localid   |
| Onyen   | onyenid      |

**hostname:**

| Type       | Definition      |
|------------|-----------------|
| Generic    | hostname        |
| Local      | local-hostname       |
| Remote     | remote-hostname |
| Diamond    | diamond         |
| Sapphire    | sapphire         |
| Longleaf 1 | longleaf-login1 |
| Longleaf 2 | longleaf-login2 |

**Comment by BarkleyBG** [comment] 2018-02-06 15:23
I think that after merging in #83 and #52 (and we have no more long-running branches) then we should take care of standarizing the examples. It seems to me that we should wait until we've merged the big topic branches so we can hopefully take care of changing all instances of outdated nomenclature at the same time.

**Closed** 2018-04-12 19:36 UTC
Labels: code
